-- Corregir acentos y terminar renombrado
UPDATE reprises SET nombre = 'Experimental 4 años' WHERE codigo = 'RFHE-2022-CJ4-EXP';
UPDATE reprises SET nombre = 'Final 4 años'        WHERE codigo = 'RFHE-2022-CJ4-FIN';
UPDATE reprises SET nombre = 'Preliminar 4 años'   WHERE codigo = 'RFHE-2022-CJ4-PRE';
UPDATE reprises SET nombre = 'Final 5 años'        WHERE codigo = 'RFHE-2022-CJ5-FIN';
UPDATE reprises SET nombre = 'Preliminar 5 años'   WHERE codigo = 'RFHE-2022-CJ5-PRE';
UPDATE reprises SET nombre = 'Final 6 años'        WHERE codigo = 'RFHE-2022-CJ6-FIN';
UPDATE reprises SET nombre = 'Preliminar 6 años'   WHERE codigo = 'RFHE-2022-CJ6-PRE';
UPDATE reprises SET nombre = 'Final 7 años'        WHERE codigo = 'RFHE-2022-CJ7-FIN';
UPDATE reprises SET nombre = 'Final 7 años'        WHERE codigo = 'RFHE-2022-CJ7-FIN2';
UPDATE reprises SET nombre = 'Preliminar 7 años'   WHERE codigo = 'RFHE-2022-CJ7-PRE';
UPDATE reprises SET nombre = 'Gran Premio CJ 8-10 años' WHERE codigo = 'RFHE-2022-CJ8-10';
UPDATE reprises SET nombre = 'Clásica 1' WHERE codigo = 'RFHE-2023-CLA-1';
UPDATE reprises SET nombre = 'Clásica 2' WHERE codigo = 'RFHE-2023-CLA-2';
UPDATE reprises SET nombre = 'Clásica 3' WHERE codigo = 'RFHE-2023-CLA-3';
UPDATE reprises SET nombre = 'Kür Gran Premio'    WHERE codigo = 'RFHE-2022-KUR-GP';
UPDATE reprises SET nombre = 'Kür Intermedia A/B' WHERE codigo = 'RFHE-2022-KUR-INT-AB';
UPDATE reprises SET nombre = 'Kür Intermedia I'   WHERE codigo = 'RFHE-2022-KUR-INT-I';
UPDATE reprises SET nombre = 'Kür Jóvenes Jinetes' WHERE codigo = 'RFHE-2022-KUR-JJ';
UPDATE reprises SET nombre = 'Kür Juveniles'      WHERE codigo = 'RFHE-2022-KUR-JUV';
UPDATE reprises SET nombre = 'Kür Juveniles 0*'   WHERE codigo = 'RFHE-2022-KUR-JUV0';
UPDATE reprises SET nombre = 'Kür Ponis'          WHERE codigo = 'RFHE-2022-KUR-PON';
UPDATE reprises SET nombre = 'Jóvenes Jinetes Equipos (San Jorge)' WHERE codigo = 'RFHE-2022-JJ-EQU';
UPDATE reprises SET nombre = 'Jóvenes Jinetes Individual'          WHERE codigo = 'RFHE-2022-JJ-IND';
UPDATE reprises SET nombre = 'Jóvenes Jinetes Preliminar'          WHERE codigo = 'RFHE-2022-JJ-PRE';
UPDATE reprises SET nombre = 'Promoción 1' WHERE codigo = 'RFHE-2022-PRO-1';
UPDATE reprises SET nombre = 'Promoción 2' WHERE codigo = 'RFHE-2024-PRO-2';
UPDATE reprises SET nombre = 'Promoción 3' WHERE codigo = 'RFHE-2022-PRO-3';
UPDATE reprises SET nombre = 'Promoción 4' WHERE codigo = 'RFHE-2022-PRO-4';
UPDATE reprises SET nombre = 'Asiento y Posición preliminar' WHERE codigo = 'RFHE-AP-PRE';
UPDATE reprises SET nombre = 'Asiento y Posición final'      WHERE codigo = 'RFHE-AP-FIN';
SELECT codigo, nombre FROM reprises ORDER BY codigo;