INSERT INTO reprises (numero, nombre, codigo, categoria, nivel, tipo, anio, tiempo_orientativo, edad_minima_caballo, total_maximo, reprise_oficial, descripcion, multiplicador, desviacion, fei_numero)
VALUES ('42', 'Gran Premio', 'RFHE-2022-GP', 'Gran Premio', 'Gran Premio', 'individual', 2022, '6''30"', 8, 440, 'GRAN PREMIO 2022', 'Reprise Gran Premio', 1, 0, 'RFHE-2022-GP');

INSERT INTO ejercicios_reprise (reprise_id, numero_orden, letra, descripcion, coeficiente, tipo)
VALUES
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 1, 'A X XC', 'Entrada al galope reunido. Parada - inmovilidad - saludo. Partir al trote reunido. Trote reunido', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 2, 'C HXF FAK', 'Pista a mano izquierda. Trote largo. Trote reunido', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 3, 'KB', 'Apoyar a la derecha', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 4, 'BH HC', 'Apoyar a la izquierda. Trote reunido', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 5, 'C', 'Parada - inmovilidad. 5 pasos atrás y partir inmediatamente al trote reunido', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 6, 'MV', 'Trote largo', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 7, 'VK D', 'Passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 8, 'D', 'Piaffe 12 a 15 batidas', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 9, 'D', 'Transiciones passage - piaffe - passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 10, 'DFP', 'Passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 11, 'PH', 'Paso largo', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 12, 'HCM', 'Paso reunido', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 13, 'M', 'Partir en Passage. Transición paso reunido - passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 14, 'MRI', 'Passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 15, 'I', 'Piaffe 12 a 15 batidas', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 16, 'I', 'Transiciones passage - piaffe - passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 17, 'ISE', 'Passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 18, 'E', 'Partir a galope reunido a mano izquierda', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 19, 'FXH', 'En la diagonal, 9 cambios de pie en el aire cada 2 trancos', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 20, 'MXK', 'Galope largo', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 21, 'K', 'Galope reunido y cambio de pie en el aire', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 22, 'A Entre D y G', 'Doblar a lo largo. 5 apoyos a un lado y otro de la línea central cambiando de pie en cada cambio de dirección, el primer apoyo a la izquierda y el último a la izquierda de 3 trancos, los otros de 6 trancos', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 23, 'G C', 'Cambio de pie. Pista a la derecha', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 24, 'MXK KAF', 'En la diagonal 15 cambios de pie en el aire al trance. Galope reunido', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 25, 'A L', 'Doblar a lo largo. Pirueta a la izquierda', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 26, 'X', 'Cambio de pie en el aire', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 27, 'I C', 'Pirueta a la derecha. Pista a la derecha', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 28, 'M MR', 'Trote reunido. Trote reunido', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 29, 'RK K KA', 'Trote largo. Trote reunido. Trote reunido', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 30, 'A DX', 'Doblar a lo largo. Passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 31, 'X', 'Piaffe 12 a 15 batidas', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 32, 'X', 'Transiciones passage - piaffe - passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 33, 'XG', 'Passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GP'), 34, 'G', 'Parada - inmovilidad - saludo', 1, 'movimiento');
