INSERT INTO reprises (numero, nombre, codigo, categoria, nivel, tipo, anio, tiempo_orientativo, edad_minima_caballo, total_maximo, reprise_oficial, descripcion, multiplicador, desviacion, fei_numero)
VALUES ('43', 'Gran Premio Especial', 'RFHE-2022-GPE', 'Gran Premio', 'Gran Premio Especial', 'individual', 2022, '6''40"', 8, 450, 'GRAN PREMIO ESPECIAL 2022', 'Reprise Gran Premio Especial', 1, 0, 'RFHE-2022-GPE');

INSERT INTO ejercicios_reprise (reprise_id, numero_orden, letra, descripcion, coeficiente, tipo)
VALUES
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 1, 'A X XC', 'Entrada al galope reunido. Parada - inmovilidad - saludo. Partir al trote reunido. Trote reunido', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 2, 'C MXK KAFP', 'Pista a mano derecha. Trote largo. Trote reunido', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 3, 'PS SHC', 'Apoyo a la izquierda. Trote reunido', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 4, 'CMR', 'Passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 5, 'RF', 'Trote largo', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 6, 'Transiciones', 'Transiciones passage - trote largo - passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 7, 'FAK', 'Passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 8, 'KV VR RMC', 'Trote reunido. Apoyo. Trote reunido', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 9, 'CHS', 'Passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 10, 'SK', 'Trote largo', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 11, 'Transiciones', 'Transiciones passage - trote largo - passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 12, 'KAF', 'Passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 13, 'FS', 'Paso largo', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 14, 'SHG', 'Paso reunido', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 15, 'G', 'Piaffe 12 a 15 batidas', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 16, 'G', 'Transiciones paso reunido - piaffe - passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 17, 'GMRI', 'Passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 18, 'I', 'Piaffe de 12 a 15 batidas', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 19, 'I', 'Transiciones de passage - piaffe - passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 20, 'ISEX', 'Passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 21, 'X XBFAK', 'Partir a galope reunido a la derecha. Galope reunido', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 22, 'KB B', 'Apoyo a galope a la derecha. Cambio de pie en el aire', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 23, 'BH H HCM', 'Apoyo a galope. Cambio de pie en el aire. Galope reunido', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 24, 'MXK KAF', 'En la diagonal 9 cambios de pie en el aire cada 2 trancos. Galope reunido', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 25, 'FXH HCM', 'En la diagonal 15 cambios de pie en el aire al trance. Galope reunido', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 26, 'MXK K KA', 'Galope largo. Galope reunido y cambio de pie en el aire. Galope reunido', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 27, 'A D', 'Doblar a lo largo. Pirueta a la izquierda', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 28, 'Entre D y G', 'En la línea central 9 cambios de pie en el aire al trance', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 29, 'G C CM', 'Pirueta a la derecha. Pista a mano derecha. Galope reunido', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 30, 'M MR', 'Trote reunido. Trote reunido', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 31, 'RF F FA', 'Trote largo. Trote reunido. Trote reunido', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 32, 'A DX', 'Doblar a lo largo. Passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 33, 'X', 'Piaffe 12 a 15 batidas', 2, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 34, 'X', 'Transiciones passage - piaffe - passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 35, 'XG', 'Passage', 1, 'movimiento'),
((SELECT id FROM reprises WHERE codigo = 'RFHE-2022-GPE'), 36, 'G', 'Parada - inmovilidad - saludo', 1, 'movimiento');
